# This is a basic workflow to help you get started with Actions

name: Stepsei Manual Workflow - Three Envs 

# Controls when the action will run.
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Repository secrets
# Using OIDC
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout


# env:
#   AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  DEV: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DEV

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::075257660618:role/github.to.aws.oicd
          role-session-name: stepseigithubrolesession
          aws-region: us-east-1 #${{ env.AWS_REGION }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        id: init
        run: terraform init 
        working-directory: ./terraform-resources
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./terraform-resources
      - name: Terraform Switch Workspace Dev
        id: select-dev
        run: terraform workspace select dev
        working-directory: ./terraform-resources
      - name: Terraform Plan Dev
        id: plan-dev
        run: terraform plan -var-file="dev.tfvars" 
        working-directory: ./terraform-resources
      # - name: Terraform Apply Workspace Dev
      #   id: apply-dev
      #   run: terraform apply -var-file="dev.tfvars" -auto-approve
      #   working-directory: ./terraform-resources
      - name: Terraform Destroy Workspace Dev
        id: destroy-dev
        run: terraform destroy -var-file="dev.tfvars" -auto-approve
        working-directory: ./terraform-resources

  
  STAGE: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: STAGE
    needs: DEV

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::075257660618:role/github.to.aws.oicd
          role-session-name: stepseigithubrolesession
          aws-region: us-east-1 #${{ env.AWS_REGION }}
      - name: Terraform Init
        id: init
        run: terraform init 
        working-directory: ./terraform-resources
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./terraform-resources
      - name: Terraform Switch Workspace Stage
        id: select-dev
        run: terraform workspace select stage
        working-directory: ./terraform-resources
      - name: Terraform Plan Stage
        id: plan-stage
        run: terraform plan -var-file="stage.tfvars"
        working-directory: ./terraform-resources
      # - name: Terraform Apply Workspace Stage
      #   id: apply-stage
      #   run: terraform apply -var-file="stage.tfvars" -auto-approve
      #   working-directory: ./terraform-resources
      - name: Terraform Destroy Workspace Stage
        id: destroy-stage
        run: terraform destroy -var-file="stage.tfvars" -auto-approve
        working-directory: ./terraform-resources

  PROD: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: PROD
    needs: STAGE

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::075257660618:role/github.to.aws.oicd
          role-session-name: stepseigithubrolesession
          aws-region: us-east-1 #${{ env.AWS_REGION }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        id: init
        run: terraform init 
        working-directory: ./terraform-resources
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./terraform-resources
      - name: Terraform Switch Workspace Prod
        id: select-prod
        run: terraform workspace select prod
        working-directory: ./terraform-resources
      - name: Terraform Plan Prod
        id: plan-stage
        run: terraform plan -var-file="prod.tfvars"
        working-directory: ./terraform-resources
      # - name: Terraform Apply Workspace Prod
      #   id: apply-prod
      #   run: terraform apply -var-file="prod.tfvars" -auto-approve
      #   working-directory: ./terraform-resources
      - name: Terraform Destroy Workspace Prod
        id: destroy-prod
        run: terraform destroy -var-file="prod.tfvars" -auto-approve
        working-directory: ./terraform-resources

